### ISSUE TITLE
Invalid Point

### ISSUE THREAD

**Issue by marssystems** [scorta/GuessPrivateKey#13]
Exception in thread "Thread-5" java.lang.IllegalArgumentException: Invalid point
        at org.spongycastle.math.ec.ECAlgorithms.validatePoint(ECAlgorithms.java:193)
        at org.spongycastle.math.ec.AbstractECMultiplier.multiply(AbstractECMultiplier.java:22)
        at org.spongycastle.crypto.generators.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:73)
        at org.bitcoinj.core.ECKey.<init>(ECKey.java:179)
        at org.bitcoinj.core.ECKey.<init>(ECKey.java:168)
        at GuessKeyThread.searchForKey(GuessPrivateKey.java:128)
        at GuessKeyThread.run(GuessPrivateKey.java:66)

[hs_err_pid5204.log](https://github.com/scorta/GuessPrivateKey/files/6563270/hs_err_pid5204.log)

**Comment by scorta** [comment]
hi, what's your:
- command to run the program?
- file size of the bitcoin wallet file?

**Comment by marssystems** [comment]
java -jar GuessPrivateKey.jar 4 1bit.txt

1bit.txt is 12318kb

**Comment by scorta** [comment]
I can't say for sure. Have you tried to run the program again? And the command you use is search in random mode, which is almost pointless. At least you should try with up or down mode, eg:

```bash
java -jar GuessPrivateKey.jar 8 bit.txt up 666
# searching sequentially from 666 and upper
```

instead of 666, I'd pick a number between 2^65 and 2^66 (or some other big numbers in Bitcoin key range...). But also, I think other program like bitcrack or https://github.com/JeanLucPons/Kangaroo are better.
